default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: homey_development
  host: localhost
  username: homey_admin
  password: <%= ENV['HOMEY_POSTGRES_PASSWORD'] %>

test:
  <<: *default
  database: homey_test
  host: localhost
  username: homey_admin
  password: <%= ENV['HOMEY_POSTGRES_PASSWORD'] %>

production:
  <<: *default
  url:  <% ENV['HOMEY_POSTGRES_PRODUCTION'] %>
