default: &default
  adapter: postgresql
  encoding: unicode
  username: homey_admin
  password: <%= ENV['HOMEY_POSTGRES_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: homey_development
test:
  <<: *default
  database: homey_test

production:
  <<: *default
  database: homey_xt2t
  username: homey_admin
  host:  <% ENV['HOMEY_POSTGRES_PRODUCTION'] %>
