default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: homey_development
  host: localhost
  username: homey_admin
  password: <%= ENV['HOMEY_POSTGRES_PASSWORD'] %>

test:
  <<: *default
  database: homey_test
  host: localhost
  username: homey_admin
  password: <%= ENV['HOMEY_POSTGRES_PASSWORD'] %>

production:
  <<: *default
  username: homey_admin
  database: <%= ENV['HOMEY_POSTGRES_DB'] %>
  host: <%= ENV['HOMEY_POSTGRES_HOST'] %>
  password: <%= ENV['HOMEY_POSTGRES_PASSWORD'] %>
  port: 5432

